name: ChestShopLimiter
version: ${minecraft.plugin.version}
main: me.droreo002.cslimit.ChestShopLimiter
api-version: 1.13
depend: [ChestShop, OreoCore]
softdepend: [LuckPerms, Essentials]

commands:
  chestshoplimiter:
    aliases: [csl]
